### PR TITLE
Modify Worker::connect to use the password in the URL, as Client::connect does.

### PR DESCRIPTION
**Pull request by constlhq**
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/faktory-rs/73)

### CODE REVIEW

**Review by rustworthy — COMMENTED** [review]
This is a great catch and the correct update, thank you!

This blunder has only been possible because I never added a test for the `WorkerBuilder` _authenticated_ flow. I've just added #75 as a primer and as soon  as a more ergonomic access to the `tls` feature will be enabled (which is now work-in-progress), this case will also be covered.

**Comment by rustworthy** [comment]
I guess we need to fmt the updated module

**Comment by rustworthy** [comment]
Hey @constlhq! Thanks again for this fix!

Will you bandwidth to iterate over this once again? 
The `fmt` job on the CI is failing, should be a quick fix.

**Review by jonhoo — APPROVED** [review]
Thanks!

**Pull request merged**
