### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by ttdonovan**
Fixed clippy warnings and replaced code with recommended suggestion.

* `cargo clippy`
* `cargo fmt`

---
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/faktory-rs/25)

### CODE REVIEW

**Comment by ttdonovan** [comment]
@jonhoo could you provide some insight into why the minimum support Rust version is 1.42?

**Comment by jonhoo** [comment]
Thanks for doing this!

@ttdonovan Purely because I went for the lowest supported version at the time of implementation. I'd be happy to bump it, though I'd prefer to stay with a version that's at least six months old (~4 releases, so <=1.51).

**Comment by ttdonovan** [comment]
That seems reasonable `strip_prefix` has been in stable since 1.45 so hopefully a bump in the Rust version will get CI passing again.

https://doc.rust-lang.org/std/string/struct.String.html#method.strip_prefix

Would it also be possible to add the a step in the Azure pipeline to check `cargo fmt` and `cargo clippy`?

**Comment by jonhoo** [comment]
> That seems reasonable `strip_prefix` has been in stable since 1.45 so hopefully a bump in the Rust version will get CI passing again.

You should be able to do that by just modifying this line:

https://github.com/jonhoo/faktory-rs/blob/5d5308c7958ec6d53e4ab6af621a1cc9115ea9af/azure-pipelines.yml#L4

> Would it also be possible to add the a step in the Azure pipeline to check `cargo fmt` and `cargo clippy`?

There's already a step for that — "Style linting" :)

**Review by jonhoo — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
